config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tasks
  resources :users
  root 'tasks#index'

  get 'users/:id' => 'users#show'

end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :user
	validates :title, :description, :presence => true
	validates :hour, :numericality => {:only_integer => true}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :tasks
         validates :username, :name, :lastname, :email, :presence=> true
  def fullname
    name + ' ' + lastname
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
protected
 
def configure_permitted_parameters
  devise_parameter_sanitizer.for(:sign_up) do |u|
    u.permit(:name, :lastname, :email, :password, :password_confirmation)
  end
  devise_parameter_sanitizer.for(:account_update) do |u|
    u.permit(:username, :name, :lastname, :email, :password, :password_confirmation, :current_password)
  end
end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all.order(finaldate: :desc)
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :description, :hour, :initialdate, :finaldate, :user_id, :finished)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  respond_to :html
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :name, :lastname)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flass_class(type)
    case type
      when :success then "success"
      when :error   then "warning"
      when :alert   then "warning"
      when :notice  then "info"
      else "info"
    end
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    
    <nav class="top-bar" data-topbar>
      <ul class="title-area">
        <li class="name">
          <h1>
            <%= link_to t('Instagram'), root_path %>
          </h1>
        </li>
        <li class="toggle-topbar menu-icon">
          <a href="#"><span><%= t('Menu') %></span></a>
        </li>
      </ul>

      <section class="top-bar-section">
        <ul class="left">
          <li class="divider">

          </li>
          <li>
            <%= link_to t('Users'), users_path %>
          </li>
        </ul>

        <ul class="right">
          <% if user_signed_in? %>
          <li>
            <%= link_to current_user.fullname, edit_user_registration_path %>
          </li>
          <li>
            <%= link_to t('Sign Out'), destroy_user_session_path, method: :delete %>
          </li>
          <% else %>
          <li class="active">
            <%= link_to t('Sign Up'), new_user_registration_path %>
          </li>
          <li>
            <%= link_to t('Sign In'), new_user_session_path %>
          </li>
          <% end %>
        </ul>
      </section>
    </nav>
    <div class="row">
    	<div class="columns large-12">
    		<%= yield %>
    	</div>
    </div>

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :hour %><br>
    <%= f.number_field :hour %>
  </div>
  <div class="field">
    <%= f.label :initialdate %><br>
    <%= f.date_select :initialdate %>
  </div>
  <div class="field">
    <%= f.label :finaldate %><br>
    <%= f.date_select :finaldate %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :finished %><br>
    <%= f.check_box :finished %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>
<h2>Not finished</h2>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Hour</th>
      <th>Initialdate</th>
      <th>Finaldate</th>
      <th>User</th>
      <th>Finished</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
    <%if task.finished == false%>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.hour %></td>
        <td><%= task.initialdate %></td>
        <td><%= task.finaldate %></td>
        <td><%= task.user.fullname %></td>
        <td><%= task.finished %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <%end%>
    <% end %>
  </tbody>
</table>
<h2>finished</h2>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Hour</th>
      <th>Initialdate</th>
      <th>Finaldate</th>
      <th>User</th>
      <th>Finished</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
    <%if task.finished == true%>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.hour %></td>
        <td><%= task.initialdate %></td>
        <td><%= task.finaldate %></td>
        <td><%= task.user.fullname %></td>
        <td><%= task.finished %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>


<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Hour:</strong>
  <%= @task.hour %>
</p>

<p>
  <strong>Initialdate:</strong>
  <%= @task.initialdate %>
</p>

<p>
  <strong>Finaldate:</strong>
  <%= @task.finaldate %>
</p>

<p>
  <strong>User:</strong>
  <%= @task.user_id %>
</p>

<p>
  <strong>Finished:</strong>
  <%= @task.finished %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Name</th>
      <th>Lastname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.name %></td>
        <td><%= user.lastname %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @user.lastname %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>